# Generated by Django 2.2.7 on 2020-04-02 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='정당이름')),
            ],
        ),
        migrations.CreateModel(
            name='PartyPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='순번')),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('category', models.CharField(max_length=255, verbose_name='분야')),
                ('desc', models.TextField(verbose_name='내용')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='get_data.Party')),
            ],
        ),
    ]
