# Generated by Django 2.2.7 on 2020-04-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candi_id', models.CharField(max_length=200, verbose_name='후보자ID')),
                ('sggname', models.CharField(max_length=200, verbose_name='선거구명')),
                ('sdname', models.CharField(max_length=200, verbose_name='시도명')),
                ('wiwname', models.CharField(max_length=200, verbose_name='구시군명')),
                ('jdname', models.CharField(max_length=200, verbose_name='정당이름')),
                ('name', models.CharField(max_length=200, verbose_name='이름')),
                ('gender', models.CharField(max_length=10, verbose_name='성별')),
                ('birth', models.CharField(max_length=100, verbose_name='생년월일')),
                ('age', models.IntegerField(verbose_name='연령')),
                ('addr', models.CharField(max_length=200, verbose_name='주소')),
                ('job', models.CharField(max_length=200, verbose_name='직업')),
                ('edu', models.CharField(max_length=255, verbose_name='학력')),
                ('career1', models.CharField(max_length=255, verbose_name='경력1')),
                ('career2', models.CharField(max_length=255, verbose_name='경력2')),
                ('status', models.CharField(max_length=200, verbose_name='등록상태')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='party',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='partypolicy',
            options={'ordering': ['id']},
        ),
    ]
