# Generated by Django 2.2.7 on 2020-04-03 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0002_auto_20200403_0303'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='행정구역')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
