# Generated by Django 2.2.7 on 2020-04-03 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0003_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gungu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='군구이름')),
                ('sgg_name', models.CharField(max_length=100, verbose_name='선거구이름')),
                ('sd_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='get_data.City')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
