# Generated by Django 2.2.7 on 2020-04-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0004_gungu'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='giho_num',
            field=models.CharField(default=1, max_length=100, verbose_name='기호'),
            preserve_default=False,
        ),
    ]
