# Generated by Django 2.2.7 on 2020-04-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0006_auto_20200403_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='attend',
            field=models.CharField(default='미확인', max_length=100, verbose_name='본회의 출석률'),
            preserve_default=False,
        ),
    ]
